spring:
  redis:
    database: 1 # 数据库索引
    host: localhost
    port: 6379
    password: yingzigeniub666
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/album?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      password: qiaozhiling
      username: qiao
      connection-error-retry-attempts: 3
      login-timeout: 3000
      kill-when-socket-read-timeout: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

mybatis:
  type-aliases-package: com.qiao.album.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

server:
  tomcat:
    max-http-form-post-size: 8192
  ssl:
    enabled: false
  port: 8081
  white: /user/token, /user/new, /, /v2/api-docs, /api/*, /webjars/*, /swagger*, /csrf, /image/get/*
  servlet:
    context-path: /a
    encoding:
      charset: UTF-8

myjwt:
  expire: 604800 # 七天 单位s
  secret: hjl43L*o3#OG904_Ggo@#SOihj
  startWith: ""
  header: Authorization
  redisKey: 'login:'

images:
  path: 'C:\wwwroot\qiao'

swagger:
  enable: true
  application-name: 云相册接口文档!!
  application-version: 1.0
  application-description: 只是接口文档，测试功能没有维护，用来看的。测试环境Postman v9.21.2，测完再写！就你麻烦sbhr

logging:
  level:
    root: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error